### ISSUE TITLE
scape metrics from multiple containers in docker swarm

### ISSUE THREAD

**Issue by TheFatal** [nginxinc/nginx-prometheus-exporter#138]
I have a little swarm cluster with 6 nodes and I deploy 2 replicas of nginx on it:

  ```
nginx:
    image: registry:5000/nginx:2
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 2
```

Is it possible to scape metrics from every replica via nginx-exporter ?

**Comment by pleshakov** [comment]
Hi @TheFatal 

the exporter can only scape metrics from one replica. For each replica, you will need to have a dedicated exporter.

**Comment by ffroliva** [comment]
Can you provide an example of docker-compose.yml?

Would it be possible to dynamically get the docker container IP?

**Comment by akerouanton** [comment]
@ffroliva Here's how I solved this problem:

In my swarm file, I've got:
```
services:
  nginx:
    # This is required to let each instance of the nginx-exporter access a specific task.
    hostname: 'nginx-{{.Task.Slot}}'
    deploy:
      mode: replicated
      replicas: 2

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    environment:
      - SCRAPE_URI=http://nginx-{{.Task.Slot}}/status
    networks:
      default: {}
      prometheus: {}
    deploy:
      mode: replicated
      # This service has to have as many replicas as nginx service.
      replicas: 2
```

And in my `prometheus.yml`:

```
  - job_name: nginx-exporter
    dns_sd_configs:
      - names: ['front-nginx-exporter']
        type: A
        port: 9113
```
