### ISSUE TITLE
docker compose doesnt running the container with adding scrape-uri param

### ISSUE THREAD

**Issue by Fadih** [nginxinc/nginx-prometheus-exporter#30]
**Describe the bug**
im  running nginx exporter using docker compose 
i have this compose file 

> `
version: '2'
services:

  prometheus:
    image: nginx/nginx-prometheus-exporter:0.2.0
    user: root
    volumes:
      - /monitoring:/monitoring
    command:
      - '-nginx.scrape-uri http://x.x.x.x:80/nginx_status'
    ports:
      - "9113:9113"
    restart: unless-stopped
> 
`
when running this command docker-compose up i got this error 

flag provided but not defined: -nginx.scrape-uri http://x.x.x.x:80/nginx_status

**Comment by Fadih** [comment]
fixed by using environment variable 
    environment:
      - SCRAPE_URI=http://100.127.21.218:80/nginx_status

**Comment by pleshakov** [comment]
@Fadih 
this should help as well:
```
 command:
    - -nginx.scrape-uri
    - http://x.x.x.x:80/nginx_status
```

**Comment by iobelika** [comment]
Can anyone provide the correct and full docker-compose file for this? Thnx!

**Comment by pleshakov** [comment]
@iobelika 
Here is an example of a Docker compose:
```yaml
version: '3'

services:
  prometheus-nginx:
    image: nginx-prometheus-exporter
    ports:
    - "8081:9113"
    entrypoint:
    - /usr/bin/exporter
    - -nginx.scrape-uri
    - http://demo.nginx.com/stub_status
  prometheus-nginx-plus:
    image: nginx-prometheus-exporter
    ports:
    - "8082:9113"
    entrypoint:
    - /usr/bin/exporter
    - -nginx.plus
    - -nginx.scrape-uri
    - http://demo.nginx.com/api/
```
In this example we run two exporter containers - one for NGINX OSS metrics expose via http://demo.nginx.com/stub_status and one for NGINX Plus metrics exposed via http://demo.nginx.com/api/
 Hope this helps!

**Comment by junejie** [comment]
This config works for me
```                                                             
  prometheus_nginx:                                                                                                   
    image: nginx/nginx-prometheus-exporter:0.9.0                                                                      
    ports:                                                                                                            
    - "9113:9113"                                                                                                     
    command:                                                                                                          
    - -nginx.scrape-uri                                                                                               
    - http://<your ip>/stub_status      
```
