### ISSUE TITLE
Metrics not enough

### ISSUE THREAD

**Issue by 631068264** [nginxinc/nginx-prometheus-exporter#328]
**Describe the bug**

**To reproduce**

use rancher/nginx-ingress-controller:nginx-1.2.0-rancher1 as nginx-ingress-controller

use nginx/nginx-prometheus-exporter:0.11.0  as controller sidecar

```yaml
  - args:
    - -nginx.scrape-uri=http://127.0.0.1/nginx_status
    - ""
    image: nginx/nginx-prometheus-exporter:0.11.0
    imagePullPolicy: Always
    name: exporter
    ports:
    - containerPort: 9113
      name: prometheus
      protocol: TCP
```

only get metrics
```
# HELP nginx_connections_accepted Accepted client connections
# TYPE nginx_connections_accepted counter
nginx_connections_accepted 15934
# HELP nginx_connections_active Active client connections
# TYPE nginx_connections_active gauge
nginx_connections_active 1
# HELP nginx_connections_handled Handled client connections
# TYPE nginx_connections_handled counter
nginx_connections_handled 15934
# HELP nginx_connections_reading Connections where NGINX is reading the request header
# TYPE nginx_connections_reading gauge
nginx_connections_reading 0
# HELP nginx_connections_waiting Idle client connections
# TYPE nginx_connections_waiting gauge
nginx_connections_waiting 0
# HELP nginx_connections_writing Connections where NGINX is writing the response back to the client
# TYPE nginx_connections_writing gauge
nginx_connections_writing 1
# HELP nginx_http_requests_total Total http requests
# TYPE nginx_http_requests_total counter
nginx_http_requests_total 15934
# HELP nginx_up Status of the last metric scrape
# TYPE nginx_up gauge
nginx_up 1
# HELP nginxexporter_build_info Exporter build information
# TYPE nginxexporter_build_info gauge
nginxexporter_build_info{arch="linux/amd64",commit="e4a6810d4f0b776f7fde37fea1d84e4c7284b72a",date="2022-09-07T21:09:51Z",dirty="false",go="go1.19",version="0.11.0"} 1
```

**Expected behavior**

**Your environment**
* Version of the Prometheus exporter - release version or a specific commit  0.11.0
* Version of Docker/Kubernetes  v1.23.6
* [if applicable] Kubernetes platform (e.g. Mini-kube or GCP)  rke
* Using NGINX or NGINX Plus  nginx

**Additional context**
Add any other context about the problem here. Any log files you want to share.
